In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import tensorflow as tf
from collections import Counter

%matplotlib inline

In [71]:
#race = "white"
race = "hispanic"
#race = "mixed"

In [72]:
if race == "white":
    data = pd.read_csv("../Data/white/white_2year.csv")
if race == "hispanic":
    data = pd.read_csv("../Data/hispanic/hispanic_2year.csv")
if race == "mixed":
    data = pd.read_csv("../Data/mixed/mixed_2year.csv")
data_matrix = data.as_matrix()

In [45]:
data.head()

pubcsnum  mar_stat  sex primsite  histo3v  beho3v  grade  dx_conf  csexten  \
0   7000085         5    1     C199     8210       3      2        1      160   
1   7000085         9    1     C180     8140       3      2        1      600   
2   7000321         5    2     C187     8210       3      1        1      200   
3   7000411         5    2     C187     8480       3      2        1      450   
4   7000472         5    2     C199     8020       3      4        1      999   

   cslymphn        ...          eod10_pn  eod10_ne  cstumsiz  maligcount  \
0         0        ...                98         0       999           4   
1       300        ...                97        98        40           4   
2         0        ...                 0         2         8           2   
3       200        ...                 1        11        75           2   
4         0        ...                98         0       999           3   

   benbordcount  year_dx  nhiade  codpub  srv_time_mon  srv_time_mon_flag  
0             0     2007       0   21040            47                  1  
1             0     2007       0   21040            47                  1  
2             0     2012       0       0            39                  1  
3             0     2006       0   21040            38                  1  
4             0     2009       0   21050             0                  1  

[5 rows x 29 columns]

In [46]:
data_matrix.shape

(275547, 29)

In [47]:
data_matrix[0]

array([7000085, 5, 1, 'C199', 8210, 3, 2, 1, 160, 0, 0, 3.0, 0.0, 0.0, 26,
       0, 1, 1502, 77, 98, 0, 999, 4, 0, 2007, 0, 21040, 47, 1], dtype=object)

# Preprocessing

In [73]:
# Y2 will be indicator of survival; 21040 and 21050 are SEER codes for colon and rectum cancer
Y2 = np.logical_not(np.logical_and(data_matrix[:,-2].astype(int)<24, np.isin(data_matrix[:,-3], (21040, 21050))))
X = data_matrix[:,1:23]

In [49]:
print(X[0])
Counter(X[:,-2])

[5 1 'C199' 8210 3 2 1 160 0 0 3.0 0.0 0.0 26 0 1 1502 77 98 0 999 4]


Counter({0: 422,
         1: 827,
         2: 1215,
         3: 1441,
         4: 1330,
         5: 1903,
         6: 1230,
         7: 1138,
         8: 1280,
         9: 797,
         10: 3225,
         11: 769,
         12: 1594,
         13: 982,
         14: 809,
         15: 4595,
         16: 826,
         17: 1284,
         18: 1461,
         19: 626,
         20: 7468,
         21: 890,
         22: 2055,
         23: 1252,
         24: 1079,
         25: 8529,
         26: 1133,
         27: 1605,
         28: 1763,
         29: 737,
         30: 13588,
         31: 885,
         32: 2577,
         33: 1328,
         34: 1047,
         35: 10546,
         36: 1060,
         37: 1645,
         38: 1806,
         39: 611,
         40: 15640,
         41: 728,
         42: 2131,
         43: 1268,
         44: 718,
         45: 9590,
         46: 780,
         47: 1241,
         48: 1330,
         49: 417,
         50: 14812,
         51: 525,
         52: 1397,
         53: 859

In [50]:
X[0]

array([5, 1, 'C199', 8210, 3, 2, 1, 160, 0, 0, 3.0, 0.0, 0.0, 26, 0, 1,
       1502, 77, 98, 0, 999, 4], dtype=object)

In [74]:
X_cat = X[:,:-5]
# primary site is only categorical variable with string labels
X_primsite = X[:,2]
X_cont = X[:,-5:]
# X_cat contains only categorical variables with integer labels
X_cat = np.delete(X_cat, [2], axis=1)

In [81]:
X_cat.shape

(37575, 16)

In [76]:
# Fill missing values in three eval columns with 9: unknown
# remember: index shifted over one since we deleted primsite
X_cat[:,9] = np.array([9 if np.isnan(x) else x for x in X_cat[:,9]])
X_cat[:,10] = np.array([9 if np.isnan(x) else x for x in X_cat[:,10]])
X_cat[:,11] = np.array([9 if np.isnan(x) else x for x in X_cat[:,11]])

In [77]:
# one-hot encode primary site
from sklearn.preprocessing import LabelBinarizer
from sklearn.externals import joblib


if race == "mixed":
    encoder_bin = LabelBinarizer().fit(X_primsite)
    print(encoder_bin.classes_)
    print(len(encoder_bin.classes_), "classes")
    joblib.dump(encoder_bin, "encoder_bin.pkl")

encoder_bin = joblib.load("encoder_bin.pkl")
X_primsite_1hot = encoder_bin.transform(X_primsite)

In [78]:
encoder_bin.classes_

array(['C180', 'C181', 'C182', 'C183', 'C184', 'C185', 'C186', 'C187',
       'C188', 'C189', 'C199', 'C209', 'C260'],
      dtype='<U4')

In [79]:
# one-hot encode remaining categorical variables
from sklearn.preprocessing import OneHotEncoder

if race == "mixed":
    encoder_1hot = OneHotEncoder(sparse=False).fit(X_cat)
    joblib.dump(encoder_1hot, "encoder_1hot.pkl")

encoder_1hot = joblib.load("encoder_1hot.pkl")
X_cat_1hot = encoder_1hot.transform(X_cat)

In [86]:
encoder_1hot.feature_indices_

array([    0,    10,    13,  9594,  9598,  9608,  9618, 10618, 11618,
       11718, 11728, 11738, 11748, 11848, 11858, 11868, 13416])

In [89]:
encoder_1hot.get_params()

{'categorical_features': 'all',
 'dtype': numpy.float64,
 'handle_unknown': 'error',
 'n_values': 'auto',
 'sparse': False}

In [55]:
# combine all categorical variables
X_cat = np.hstack((X_primsite_1hot, X_cat_1hot))
X_cat.shape

(275547, 370)

The continuous variables in order: age_dx, eod10_pn, eod10_ne, cstumsiz, maligcount. Age and maligcount do not require imputation, and eod10_ne (nodes examined) will not be used as a variable.


Here we will impute values for eod10_pn and cstumsiz. We will implement multivariate imputation by chained equations (MICE) on these two continuous variables. Their indices are and values which need to be imputed are:

1: eod10_pn (95, 97, 98, 99)<br>
3: cstumsiz (998, 999)<br>

Additionally, we will replace the values (991, 992, 993, 994, 995) in cstumsiz with (1, 2, 3, 4, 5) respectively.


### Note: The above should be re-verified for each different dataset. This is for colorectal cancer in Hispanic patients after 2004.

In [56]:
Counter(X_cont[:,3])

Counter({0: 422,
         1: 827,
         2: 1215,
         3: 1441,
         4: 1330,
         5: 1903,
         6: 1230,
         7: 1138,
         8: 1280,
         9: 797,
         10: 3225,
         11: 769,
         12: 1594,
         13: 982,
         14: 809,
         15: 4595,
         16: 826,
         17: 1284,
         18: 1461,
         19: 626,
         20: 7468,
         21: 890,
         22: 2055,
         23: 1252,
         24: 1079,
         25: 8529,
         26: 1133,
         27: 1605,
         28: 1763,
         29: 737,
         30: 13588,
         31: 885,
         32: 2577,
         33: 1328,
         34: 1047,
         35: 10546,
         36: 1060,
         37: 1645,
         38: 1806,
         39: 611,
         40: 15640,
         41: 728,
         42: 2131,
         43: 1268,
         44: 718,
         45: 9590,
         46: 780,
         47: 1241,
         48: 1330,
         49: 417,
         50: 14812,
         51: 525,
         52: 1397,
         53: 859

In [57]:
# implements MICE imputation with linear regression model on eod10_pn and cstumsiz
from sklearn.preprocessing import Imputer
from sklearn.linear_model import LinearRegression

NUM_CYCLES=10

missing_values_pn = (95, 97, 98, 99)
missing_values_tumsiz = (998, 999)

pn = np.array(X_cont[:,1]).reshape(-1,1)
tumsiz = np.array(X_cont[:,3]).reshape(-1,1)

# non-MICE imputation
for i, size in enumerate(tumsiz):
    if size not in (990, 991, 992, 993, 994, 995):
        continue
    elif size == 990:
        tumsiz[i] = 0
    elif size == 991:
        tumsiz[i] = 1
    elif size == 992:
        tumsiz[i] = 2
    elif size == 993:
        tumsiz[i] = 3
    elif size == 994:
        tumsiz[i] = 4
    elif size == 995:
        tumsiz[i] = 5


# set missing values to -1
for i, value in enumerate(pn):
    if value in missing_values_pn:
        pn[i] = -1
for i, value in enumerate(tumsiz):
    if value in missing_values_tumsiz:
        tumsiz[i] = -1

# indices for valid and imputation-needed positions in pn and tumsiz
idx_pn_missing = np.where(pn == -1)[0]
idx_pn_valid = np.where(pn != -1)[0]
idx_tumsiz_missing = np.where(tumsiz == -1)[0]
idx_tumsiz_valid = np.where(tumsiz != -1)[0]
    
# set missing values to mean
# copy = false modifies array in place
imp_pn = Imputer(missing_values = -1, copy=False)
imp_pn.fit_transform(pn)
imp_tumsiz = Imputer(missing_values = -1, copy=False)
imp_tumsiz.fit_transform(tumsiz)


for i in np.arange(NUM_CYCLES):
    print("Cycle " + str(i+1))
    
    # fit pn
    X_ind = np.hstack((X_cat[idx_pn_valid], tumsiz[idx_pn_valid]))
    X_rep = np.hstack((X_cat[idx_pn_missing], tumsiz[idx_pn_missing]))
    lin_reg = LinearRegression()
    lin_reg.fit(X_ind, pn[idx_pn_valid])
    pn[idx_pn_missing] = lin_reg.predict(X_rep)
    pn = np.maximum(pn, 0)
    pn = np.minimum(pn, 100)
    
    # fit tumsiz
    X_ind = np.hstack((X_cat[idx_tumsiz_valid], pn[idx_tumsiz_valid]))
    X_rep = np.hstack((X_cat[idx_tumsiz_missing], pn[idx_tumsiz_missing]))
    lin_reg = LinearRegression()
    lin_reg.fit(X_ind, tumsiz[idx_tumsiz_valid])
    tumsiz[idx_tumsiz_missing] = lin_reg.predict(X_rep)
    tumsiz = np.maximum(tumsiz, 0)
    tumsiz = np.minimum(tumsiz, 990)


Cycle 1
Cycle 2
Cycle 3
Cycle 4
Cycle 5
Cycle 6
Cycle 7
Cycle 8
Cycle 9
Cycle 10


In [58]:
age_dx = np.array(X_cont[:,0])
malig = np.array(X_cont[:,4])
X = np.column_stack((X_cat, age_dx, pn, malig, tumsiz))
print(X.shape)

(275547, 374)


We save the preprocessed data to disk. They are now available for our models.

In [59]:
if race == "white":
    np.save('../Data/white/X.npy', X)
    np.save('../Data/white/Y2.npy', Y2)
if race == "hispanic":
    np.save('../Data/hispanic/X.npy', X)
    np.save('../Data/hispanic/Y2.npy', Y2)
if race == "mixed":
    np.save('../Data/mixed/X.npy', X)
    np.save('../Data/mixed/Y2.npy', Y2)